version: "3"

services:
 
  main-db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./db/secrets.env
    environment:
      - MYSQL_DATABASE=vaultguarded
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  main-secrets:
    image: vault:0.9.5
# THis was used in POC version 1. It may be required again if a non-dev vault is to be used.
#    volumes:
#      - ./vault/vault.hcl:/etc/vault.hcl
    # Something about security. I think it eases setup for a development vault system
    cap_add:
      - IPC_LOCK
    ports:
      # lets you manipulate Vault from your host if you set VAULT_ADDR=http://0.0.0.0:8200
      - "8200:8200"
# command not used at the moment
#    command: "  server -config=/etc/vault.hcl"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

  appdbvault_deps:
    build: app/deps
    image: appdbvault_deps

  app:
    depends_on: appdbvault_deps
    build: app/web

    # http port for webapp
    ports:
      - "8080:5000"
    environment:
      - VAULT_TOKEN=myroot
      - APP_BOOTSTRAP_TOKEN=app-bootstrap-token
    # Splitting into 2 docker images shortens build time. Good when developing.
    depends_on:
      - appdbvault_deps
      - main-secrets
    # Mounting the volume in at startup time allows you to write code directly in the app.py file, and have the changes
    #   applied inside the running container.
    volumes:
      - ./app/web:/code

  bootstrap:
    build: app/bootstrap
    # http port for webapp
    depends_on:
      - appdbvault_deps
      - main-secrets
    # Mounting the volume in at startup time allows you to write code directly in the app.py file, and have the changes
    #   applied inside the running container.
    volumes:
      - ./app/bootstrap:/code
