version: "3"

services:
 
  main-db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./db/secrets.env
    environment:
      - MYSQL_DATABASE=vaultguarded
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  main-secrets:
    image: vault:0.9.5
# THis was used in POC version 1. It may be required again if a non-dev vault is to be used.
#    volumes:
#      - ./vault/vault.hcl:/etc/vault.hcl
    cap_add:
      - IPC_LOCK
    links:
      - main-db
    ports:
      - "8200:8200"
#    command: "  server -config=/etc/vault.hcl"
    environment:
#      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

  appdbvault_deps:
    build: app/deps

  app:
    build: app/web
    ports:
      - "8080:5000"
    environment:
      - VAULT_TOKEN=myroot
    # Splitting into 2 docker images shortens build time. Good when developing.
    depends_on:
      - appdbvault_deps
    # Mounting the volume in at startup time allows you to write code directly in the app.py file, and have the changes
    #   applied inside the running container.
    volumes:
      - ./app/web:/code

#        source: "./app"
#        target: /code
