version: "2"

services:
 
  main-db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./db/secrets.env
    environment:
      - MYSQL_DATABASE=vaultguarded
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  main-secrets:
    image: vault:0.9.5
#    volumes:
#      - ./vault/vault.hcl:/etc/vault.hcl
    cap_add:
      - IPC_LOCK
    links:
      - main-db
    ports:
      - "8200:8200"
#    command: "  server -config=/etc/vault.hcl"
    environment:
#      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=myroot

  appdbvault_deps:
    build: app/deps

  app:
    build: app/web
    ports:
      - "8080:5000"
    environment:
      - VAULT_TOKEN=myroot
    depends_on:
      - appdbvault_deps

