version: "2"

services:
  db:
    container_name: main-db
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./db/secrets.env
    environment:
      - MYSQL_DATABASE=vaultguarded
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  secrets:
    container_name: main-secrets
    image: vault
    volumes:
      - ./vault/vault.hcl:/etc/vault.hcl
    links:
      - "db:main-db"
    ports:
      - "8200:8200"
    command: "server -config=/etc/vault.hcl"
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
