version: "2"

services:
  db:
    container_name: main-db
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./secrets.env
    environment:
      - MYSQL_DATABASE=vaultguarded
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
